basket = ['a', 'x', 'b', 'c', 'd', 'e', 'd']
# print('a' in basket)
# print(basket.count('d'))
basket.sort()
# new_basket      = basket.copy()
# new_basket.sort()
# print(new_basket)
# print(basket)
# basket.reverse()
print(basket)
print(basket[::-1])